name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        -name : Checkout code 
        uses: actions/checkout@v4

        -name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        -name:  Login to DockerHub
        uses: docker/login-action@v2
        with :
         username : "ananma"
         password : "minhanh130202"

        -name : Build and push Docker image
        uses : docker/build-push-action@v5
        with :
         context : . 
         file : ./Dockerfile
         push : true 
         tags : ananma/landingpage:latest